2021-11-08 00:01:32,019 INFO 19036 [egg-logrotator] agent logger reload: got log-reload message
2021-11-08 01:00:51,585 ERROR 19036 nodejs.ClusterClientNoResponseError: client no response in 965201ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 19036
hostname: localhost

2021-11-08 01:18:39,976 ERROR 19036 nodejs.ClusterClientNoResponseError: client no response in 1048359ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 19036
hostname: localhost

2021-11-08 01:29:23,510 ERROR 19036 nodejs.ClusterClientNoResponseError: client no response in 623493ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 19036
hostname: localhost

