2022-03-22 23:59:59,725 INFO 5443 [egg-logrotator] agent logger reload: got log-reload message
2022-03-23 00:11:46,996 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 298672ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 00:39:18,327 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 291212ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 01:21:11,729 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292065ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 01:32:14,442 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 291054ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 01:43:18,129 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292053ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 02:48:39,550 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 300851ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 03:24:35,483 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 926193ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 03:41:32,762 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292107ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 03:52:51,633 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 285280ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 04:13:51,089 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292094ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 04:24:55,083 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292076ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 04:30:27,350 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292118ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 04:41:31,143 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292060ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 04:52:48,177 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 285299ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 05:19:23,664 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 295087ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 05:24:54,749 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 291066ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 05:52:47,926 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 285324ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 06:40:20,634 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292106ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 07:29:16,464 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292210ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 07:45:52,852 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292418ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 07:57:11,692 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292065ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 08:18:11,244 ERROR 5443 nodejs.ClusterClientNoResponseError: client no response in 292297ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/dazeng/IdeaProjects/lulab_backend/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
name: "ClusterClientNoResponseError"
pid: 5443
hostname: dadeMacBook-Pro.local

2022-03-23 15:36:52,760 INFO 35560 [egg:logger] init all loggers with options: {"dir":"/Users/dazeng/IdeaProjects/lulab_backend/logs/egg-graphql","encoding":"utf8","env":"local","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":false,"outputJSON":false,"buffer":true,"appLogName":"egg-graphql-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{"consoleLevel":"WARN"},"allowDebugAtProd":false,"type":"agent"}
2022-03-23 15:36:54,374 INFO 35560 [egg:core] dump config after load, 40ms
2022-03-23 15:36:54,514 INFO 35560 [egg-watcher] Start watching: ["/Users/dazeng/IdeaProjects/lulab_backend/app","/Users/dazeng/IdeaProjects/lulab_backend/config","/Users/dazeng/IdeaProjects/lulab_backend/mocks","/Users/dazeng/IdeaProjects/lulab_backend/mocks_proxy","/Users/dazeng/IdeaProjects/lulab_backend/app.js"]
2022-03-23 15:36:54,514 INFO 35560 [egg-watcher] Start watching: "/Users/dazeng/IdeaProjects/lulab_backend/app"
2022-03-23 15:36:54,514 INFO 35560 [egg-watcher] Start watching: "/Users/dazeng/IdeaProjects/lulab_backend/config"
2022-03-23 15:36:54,515 INFO 35560 [egg-watcher] Start watching: "/Users/dazeng/IdeaProjects/lulab_backend/mocks"
2022-03-23 15:36:54,515 INFO 35560 [egg-watcher] Start watching: "/Users/dazeng/IdeaProjects/lulab_backend/mocks_proxy"
2022-03-23 15:36:54,516 INFO 35560 [egg-watcher] Start watching: "/Users/dazeng/IdeaProjects/lulab_backend/app.js"
2022-03-23 15:36:54,517 INFO 35560 [egg-watcher:agent] watcher start success
2022-03-23 15:36:54,605 INFO 35560 [egg:core] dump config after ready, 5ms
